### PR TITLE
split form code

### PR DESCRIPTION
**Pull request by lalop**
Work in progress to try to axtract form ui.
related to #54

### CODE REVIEW

**Comment by lalop** [comment]
Hi @whitef0x0 ,
I will make a readonly split of the base folder into the new repository you prepared.
I don't know why but I had to add some dependencies into bower, do you have an idea why ?
Let me know if you can take a look on what I did and if it seems good for you

**Comment by lalop** [comment]
@whitef0x0 It will be more and more dificult to maintain this branch synced with master, do you think you could take a moment to make me some feedback or merge it if it seems good for you ?

**Comment by lalop** [comment]
I think I have found the tool we need to handle this split https://github.com/dflydev/dflydev-git-subsplit-github-webhook

**Comment by whitef0x0** [comment]
@lalop I will look into merging this into master today/tommorow.

**Comment by whitef0x0** [comment]
@lalop Will you want to run the git-split server or should I?

**Comment by lalop** [comment]
Actually I can't make it run, if you can this could be great otherwise I will see to do it in some weeks.

**Comment by lalop** [comment]
@whitef0x0 do you have any plan to merge this ?

**Comment by whitef0x0** [comment]
Im hesitant to merge this as I thought this was ti be a separate branch from master

**Comment by whitef0x0** [comment]
@lalop I'm getting this error when I run your merged code https://docs.angularjs.org/error/$compile/tpload?p0=modules%2Fforms%2Fviews%2FdirectiveViews%2Fform%2Fsubmit-form.client.view.html&p1=404&p2=Not%20Found

**Comment by lalop** [comment]
can you copy/paste the error please, I don't have the detail on the link

**Comment by whitef0x0** [comment]
I got the error to work but when I run the app it breaks my browser. Seems like you have a memory problem or something.

**Comment by whitef0x0** [comment]
@lalop

**Comment by lalop** [comment]
@whitef0x0 I will not be able to work on this this week.
I have no issue with the form demo, I will test the all app next week.
If you have some information on the issue let me know.

**Comment by lalop** [comment]
@whitef0x0 do you have allways the same troubles ?

**Comment by whitef0x0** [comment]
This has been merged into stage.

**Pull request closed without merging**
