### PR TITLE
add redis to docker-compose.yml

### PR DESCRIPTION
**Pull request by lalop**

### CODE REVIEW

**Comment by whitef0x0** [comment]
why isn't travis passing

**Comment by lalop** [comment]
The error says `cannot find module 'bcrypt'`
I can't see the link with this pr but maybe we should add bcrypt into package.json ?

**Comment by whitef0x0** [comment]
Yea probably. I'll run the tests on my computer tonight or tomorrow and see what's going on.

**Comment by whitef0x0** [comment]
@lalop can you add bcrypt to the package.json?

**Comment by lalop** [comment]
done,
once this will be merge I will rebase my other pr to pass travis build

**Comment by whitef0x0** [comment]
There still seems to be an error with bcrypt and node-gyp. Weird. I'll have  to look into this

**Comment by whitef0x0** [comment]
@lalop it's failing because of the npm install option. I'll change it rn

**Comment by whitef0x0** [comment]
@lalop see this https://github.com/lalop/tellform/pull/3 for fix

**Comment by lalop** [comment]
@whitef0x0 I fixed travis but there is some issue in tests

**Comment by whitef0x0** [comment]
@lalop this is just failing because I am taking over ownership of an npm dependency

**Pull request merged**
